### ISSUE TITLE
Cadastro do usuário

### ISSUE THREAD

**Issue by V1niciusTavares** [V1niciusTavares/PsicoMais#10]
como novo usuário do psicomais quero cadastrar minha conta para ter acesso a marcação de consultas no sistema

- [x] formulário
- [x] limite dos campos
- [x] campos obrigatórios

**Comment by ijbs-dev** [comment]
[Proj_Web01_Svelte_V001.tar.gz](https://github.com/V1niciusTavares/PsicoMais/files/9834173/Proj_Web01_Svelte_V001.tar.gz)

**Comment by ijbs-dev** [comment]
**Boa noite galera. 

Segue em anexo primeira versão (simples) do cadastro de usuario (Svelte, Javascript, html e css). 
Várias modificações precisarão ser realizadas, alem das possiveis futuras integrações com BD e PHP.**

**Comment by ijbs-dev** [comment]
**Boa noite galera.**

**Segue em anexo primeira versão (simples) do cadastro de usuario (Svelte, Javascript, html e css).
Várias modificações precisarão ser realizadas, alem das possiveis futuras integrações com BD e PHP.****

**Comment by ijbs-dev** [comment]
**Boa noite galera.**

**Segue em anexo primeira versão (simples) do cadastro de usuario (Svelte, Javascript, html e css).
Várias modificações precisarão ser realizadas, alem das possiveis futuras integrações com BD e PHP.**
