### ISSUE TITLE
Modelo de BD

### ISSUE THREAD

**Issue by V1niciusTavares** [V1niciusTavares/PsicoMais#13]
Nós como dev precisamos criar um banco de dados para integrar os cadastros dos nossos usuários

- [x] Modelo Relacional
- [x] Modelo Lógico
- [x] Modelo Físico

**Comment by LukeVanHagen** [comment]
[MODELO FISICO PROJETO 1.zip](https://github.com/V1niciusTavares/PsicoMais/files/9814840/MODELO.FISICO.PROJETO.1.zip)


INICIO DA MODELAGEM DO MODELO FISICO DO PROJETO

**Comment by LukeVanHagen** [comment]
[MODELO LOGICO PROJETO 1.zip](https://github.com/V1niciusTavares/PsicoMais/files/9814842/MODELO.LOGICO.PROJETO.1.zip)


INICIO DA MODELAGEM DO MODELO LÓGICO DO PROJETO

**Comment by LukeVanHagen** [comment]
![ER projeto 1](https://user-images.githubusercontent.com/109125889/196536892-44e6e897-1d65-4cb0-be0b-c97111e1e15e.PNG)


INICIO DA MODELAGEM MODELO RELACIONAL DO PROJETO

**Comment by LukeVanHagen** [comment]
21/10 



[MODELO LOGICO PROJETO 1.zip](https://github.com/V1niciusTavares/PsicoMais/files/9838721/MODELO.LOGICO.PROJETO.1.zip)

**Comment by V1niciusTavares** [comment]
aula de BD 22/11 MySQL

create database test.banco
default character set utf8
default collate utf8_general_ci;

use test.banco;

create scp_clientes(
cli_codigo int not null,
cli_nome varchar(45) not null,
cli_tipo varchar (10),
cli_contato varchar(45),
cli_cargo varchar(45),
cli_endereco varchar(45),
constraint cli_pk primary key (cli_codigo)
);

create table scp_pedidos(
    ped_codigo int,
    ped_data datetime not null,
    ped_fun_codigo int,
    ped_cli_codigo int,
    ped_frete float,
    ped_tipo_envio varchar(20),
    constraint ped_pk primary key (ped_codigo),
    foreign key (ped_cli_codigo) references 
);

create table scp_itens (
    ite_ped_codigo int not null,
    ite_pro_codigo int not null,
    ite_quantidade int not,
    ite_valor float not null,
);

create table scp_produtos (
    pro_codigo int  not null,
    pro_nome varchar(20) not null,
    pro_descricao varchar(45),
    pro_apresentacao varchar(45),
    pro_valor_venda float,
    pro_tip_codigo int not null,
    pro_qtde_estoque int,
    pro_qtde_minima int,
    pro_valor_compra int,
    
);
create table scp_tipos_produto (
    tip_codigo int not null,
    tip_nome varchar(20) not null ,
);
create table scp_funcionarios (
    fun_codigo int not null,
    fun_nome varchar(45) not null,
    fun_sexo varchar(1) not null,
    fun_estado_civil varchar(10),
    fun_rg varchar(8) not null,
    fun_cpf varchar(11) not null,
    fun_data_nasc datetime not null,
    fun_cid_codigo int not null,
    fun_set_sigla varchar(10) not null,
    fun_fnc_codigo int not null,
    fun_salario float,
    fun_telefone varchar(15),
    fun_email varchar(30),
);

obs: incompleto , favor quem completar editar aqui corretamente.

**Comment by V1niciusTavares** [comment]
codigo banco bd

create database test.banco
default character set utf8
default collate utf8_general_ci;

use test.banco;

create table scp_clientes(
cli_codigo int not null,
cli_nome varchar(45) not null,
cli_tipo varchar (10),
cli_contato varchar(45),
cli_cargo varchar(45),
cli_endereco varchar(45),
cli_cid_codigo int,
constraint cli_pk primary key (cli_codigo),
constraint cli_fk foreign key (cli_cid_codigo) references scp_cidades (cid_codigo)
);

create table scp_pedidos(
ped_codigo int not null,
ped_data datetime not null,
ped_frete float,
ped_tipo_envio varchar(20),
ped_fun_codigo int,
ped_cli_codigo int,
constraint ped_pk primary key (ped_codigo),
constraint ped_fk foreign key (ped_fun_codigo) references scp_funcionarios (fun_codigo),
constraint pedi_fk foreign key (ped_cli_codigo) references scp_clientes (cli_codigo)
);

create table scp_itens (
ite_ped_codigo int not null,
ite_pro_codigo int not null,
ite_quantidade int not,
ite_valor float not null,
constraint ite_pk primary key (ite_ped_codigo)
);

create table scp_produtos (
pro_codigo int not null,
pro_nome varchar(20) not null,
pro_descricao varchar(45),
pro_apresentacao varchar(45),
pro_valor_venda float,
pro_tip_codigo int not null,
pro_qtde_estoque int,
pro_qtde_minima int,
pro_valor_compra int,
pro_tip_codigo int,
constraint pro_pk primary key(pro_codigo),
constraint pro_fk foreign key (pro_tip_codigo) references scp_tipos_produto (tip_codigo)
);

create table scp_tipos_produto (
tip_codigo int not null,
tip_nome varchar(20) not null,
constraint tippro_pk primary key(tip_codigo)
);


create table scp_funcionarios (
fun_codigo int not null,
fun_nome varchar(45) not null,
fun_sexo varchar(1) not null,
fun_estado_civil varchar(10) not null,
fun_rg varchar(8) not null,
fun_cpf varchar(11) not null,
fun_data_nasc datetime not null,
fun_salario float,
fun_telefone varchar(15),
fun_email varchar(30),
fun_cid_codigo int,
fun_set_sigla varchar(10),
fun_fnc_codigo int,
constraint fun_pk primary key (fun_codigo),
constraint funcid_fk foreign key (fun_cid_codigo) references scp_cidades (cid_codigo),
constraint funset_fk foreign key (fun_set_sigla) references scp_setores (set_sigla),
constraint funfnc_fk foreign key (fun_fnc_codigo) references scp_funcoes (fnc_codigo)
);

create table scp_funcoes (
    fnc_codigo int not null,
    fnc_nome varchar (45) not null,
    fnc_gratificacao float,
    constraint fnc_pk primary key (fnc_codigo)
);

create table scp_setores (
 set_sigla varchar (10) not null,
 set_nome varchar (45) not null,
 set_ramal varchar (4),
 set_fun_codigo int,
 constraint set_pk primary key (set_sigla),
 constraint set_fk foreign key (set_fun_codigo) references scp_funcionarios (fun_codigo)
);

create table scp_paises(
    pai_sigla varchar (3) not null,
    pai_nome  varchar (45) not null,
    constraint pai_pk primary key (pai_sigla)
);

create table scp_cidades (
    cid_codigo int not null,
    cid_nome varchar (45) not null,
    cid_pai_sigla varchar (3),
    constraint cid_pk primary key (cid_codigo),
    constraint cid_fk foreign key (cid_pai_sigla) references scp_paises (pai_sigla)
);

**Comment by LukeVanHagen** [comment]
create database testbanco;

use psicomais;

create table scp_clientes(
cli_codigo int not null,
cli_nome varchar(45) not null,
cli_tipo varchar (10),
cli_contato varchar(45),
cli_cargo varchar(45),
cli_endereco varchar(45),
cli_cid_codigo int,
constraint cli_pk primary key (cli_codigo),
constraint cli_fk foreign key (cli_cid_codigo) references scp_cidades (cid_codigo)
);

create table scp_pedidos(
ped_codigo int not null,
ped_data datetime not null,
ped_frete float,
ped_tipo_envio varchar(20),
ped_fun_codigo int,
ped_cli_codigo int,
constraint ped_pk primary key (ped_codigo),
constraint ped_fk foreign key (ped_fun_codigo) references scp_funcionarios (fun_codigo),
constraint pedi_fk foreign key (ped_cli_codigo) references scp_clientes (cli_codigo)
);

create table scp_itens (
ite_ped_codigo int not null,
ite_pro_codigo int not null,
ite_quantidade int not null,
ite_valor float not null,
constraint ite_pk primary key (ite_ped_codigo)
);

create table scp_produtos (
pro_codigo int not null,
pro_nome varchar(20) not null,
pro_descricao varchar(45),
pro_apresentacao varchar(45),
pro_valor_venda float,
pro_tip_codigo int not null,
pro_qtde_estoque int,
pro_qtde_minima int,
pro_valor_compra int,
pro_tip_codigo int,
constraint pro_pk primary key(pro_codigo),
constraint pro_fk foreign key (pro_tip_codigo) references scp_tipos_produto (tip_codigo)
);

create table scp_tipos_produto (
tip_codigo int not null,
tip_nome varchar(20) not null,
constraint tippro_pk primary key(tip_codigo)
);

create table scp_funcionarios (
fun_codigo int not null,
fun_nome varchar(45) not null,
fun_sexo varchar(1) not null,
fun_estado_civil varchar(10) not null,
fun_rg varchar(8) not null,
fun_cpf varchar(11) not null,
fun_data_nasc datetime not null,
fun_salario float,
fun_telefone varchar(15),
fun_email varchar(30),
fun_cid_codigo int,
fun_set_sigla varchar(10),
fun_fnc_codigo int,
constraint fun_pk primary key (fun_codigo),
constraint funcid_fk foreign key (fun_cid_codigo) references scp_cidades (cid_codigo),
constraint funset_fk foreign key (fun_set_sigla) references scp_setores (set_sigla),
constraint funfnc_fk foreign key (fun_fnc_codigo) references scp_funcoes (fnc_codigo)
);

create table scp_funcoes (
fnc_codigo int not null,
fnc_nome varchar (45) not null,
fnc_gratificacao float,
constraint fnc_pk primary key (fnc_codigo)
);

create table scp_setores (
set_sigla varchar (10) not null,
set_nome varchar (45) not null,
set_ramal varchar (4),
set_fun_codigo int,
constraint set_pk primary key (set_sigla),
constraint set_fk foreign key (set_fun_codigo) references scp_funcionarios (fun_codigo)
);

create table scp_paises(
pai_sigla varchar (3) not null,
pai_nome varchar (45) not null,
constraint pai_pk primary key (pai_sigla)
);

create table scp_cidades (
cid_codigo int not null,
cid_nome varchar (45) not null,
cid_pai_sigla varchar (3),
constraint cid_pk primary key (cid_codigo),
constraint cid_fk foreign key (cid_pai_sigla) references scp_paises (pai_sigla)
);

**Comment by LukeVanHagen** [comment]
modelo da materia de BD para estudo ^^^^^^^^^^^^
